import type { ProviderConfig } from '@/types'

export const PROVIDERS: ProviderConfig[] = [
  {
    id: 'deepseek',
    name: 'DeepSeek',
    apiFormat: 'openai',
    baseUrl: 'https://api.deepseek.com/v1',
    models: ['deepseek-chat', 'deepseek-reasoner'],
    defaultModel: 'deepseek-chat',
    keyPrefix: 'sk-',
    keyPlaceholder: 'sk-...',
    docsUrl: 'https://platform.deepseek.com/api_keys',
    icon: '🧠',
    color: '#4D6BFE',
    custom: false,
  },
  {
    id: 'openai',
    name: 'OpenAI',
    apiFormat: 'openai',
    baseUrl: 'https://api.openai.com/v1',
    models: ['gpt-4o-mini', 'gpt-4o', 'gpt-4-turbo', 'gpt-3.5-turbo'],
    defaultModel: 'gpt-4o-mini',
    keyPrefix: 'sk-',
    keyPlaceholder: 'sk-proj-...',
    docsUrl: 'https://platform.openai.com/api-keys',
    icon: '🟢',
    color: '#10A37F',
    custom: false,
  },
  {
    id: 'anthropic',
    name: 'Anthropic (Claude)',
    apiFormat: 'anthropic',
    baseUrl: 'https://api.anthropic.com/v1',
    models: [
      'claude-3-5-sonnet-latest',
      'claude-3-5-haiku-latest',
      'claude-3-opus-latest',
    ],
    defaultModel: 'claude-3-5-haiku-latest',
    keyPrefix: 'sk-ant-',
    keyPlaceholder: 'sk-ant-...',
    docsUrl: 'https://console.anthropic.com/settings/keys',
    icon: '🟠',
    color: '#D4A574',
    custom: false,
  },
  {
    id: 'groq',
    name: 'Groq',
    apiFormat: 'openai',
    baseUrl: 'https://api.groq.com/openai/v1',
    models: ['llama-3.3-70b-versatile', 'llama-3.1-8b-instant', 'mixtral-8x7b-32768'],
    defaultModel: 'llama-3.3-70b-versatile',
    keyPrefix: 'gsk_',
    keyPlaceholder: 'gsk_...',
    docsUrl: 'https://console.groq.com/keys',
    icon: '⚡',
    color: '#F55036',
    custom: false,
  },
  {
    id: 'mistral',
    name: 'Mistral',
    apiFormat: 'openai',
    baseUrl: 'https://api.mistral.ai/v1',
    models: ['mistral-small-latest', 'mistral-large-latest', 'open-mistral-nemo'],
    defaultModel: 'mistral-small-latest',
    keyPrefix: '',
    keyPlaceholder: '...',
    docsUrl: 'https://console.mistral.ai/api-keys/',
    icon: '🌬️',
    color: '#FF7000',
    custom: false,
  },
  {
    id: 'custom',
    name: 'Custom (OpenAI-compatible)',
    apiFormat: 'openai',
    baseUrl: '',
    models: [],
    defaultModel: '',
    keyPrefix: '',
    keyPlaceholder: 'your-api-key',
    docsUrl: '',
    icon: '⚙️',
    color: '#6B7280',
    custom: true,
  },
]

const PROVIDER_MAP = new Map(PROVIDERS.map((p) => [p.id, p]))

export function getProvider(id: string): ProviderConfig {
  return PROVIDER_MAP.get(id) ?? PROVIDERS[0]
}
